version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27018:27017'
    volumes:
      - databases:/data/db

volumes:
  databases:
    external: true
    name: mongo_data
